language: cpp
compiler:
  - gcc
  - clang
env:
  - QT=qt5 CONFIG=shared
  - QT=qt5 CONFIG=static
  - QT=qt4 CONFIG=shared
  - QT=qt4 CONFIG=static
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev
script:
  - nproc
  - qmake -qt=${QT} -v
  - ./configure -verbose -config ${CONFIG} -qmake `qmake -qt=${QT} -query QT_INSTALL_BINS`/qmake -var "QMAKE_CXX=${CXX}" -var "QMAKE_CC=${CC}"
  - make -j$(nproc)
  - make check
  - sudo make install
  - cd tests/build
  - qmake -qt=${QT} && make
notifications:
  email:
    recipients:
      - jpnurmi@gmail.com
    on_success: never
    on_failure: always
  irc:
    channels:
      - "irc.freenode.org#communi"
    template:
     - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} - %{build_url}"
    use_notice: true
    skip_join: true
